# Generated by Django 5.2.16 on 2026-07-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='슬러그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResultTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('LEGENDARY_MINORITY', '전설의 소수파'), ('RARE', '희귀한 선택'), ('MINORITY', '소수 취향'), ('BALANCED', '팽팽한 선택'), ('MAJORITY', '공감받는 선택'), ('POPULAR', '인기 선택'), ('OVERWHELMING', '압도적인 선택')], max_length=30, verbose_name='등급')),
                ('title', models.CharField(max_length=200, verbose_name='제목 템플릿')),
                ('description', models.TextField(verbose_name='설명 템플릿')),
                ('keywords', models.JSONField(default=list, verbose_name='키워드')),
                ('share_text', models.CharField(max_length=300, verbose_name='공유 문구 템플릿')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '결과 템플릿',
                'verbose_name_plural': '결과 템플릿 목록',
                'ordering': ['grade', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='양자택일.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='코드')),
                ('text', models.CharField(max_length=300, verbose_name='선택지 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='choices/', verbose_name='이미지')),
                ('vote_count', models.PositiveIntegerField(default=0, verbose_name='투표수')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='양자택일.question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '선택지',
                'verbose_name_plural': '선택지 목록',
                'ordering': ['code'],
                'unique_together': {('question', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='세션 키')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='투표일')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='양자택일.choice', verbose_name='선택지')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='양자택일.question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '투표',
                'verbose_name_plural': '투표 목록',
                'constraints': [models.UniqueConstraint(fields=('question', 'session_key'), name='unique_vote_per_session')],
            },
        ),
    ]
