# Generated by Django 5.2.16 on 2026-07-24 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('양자택일', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='주제')),
                ('description', models.TextField(blank=True, verbose_name='주제 설명')),
                ('content_basis', models.CharField(choices=[('HYPOTHETICAL', '가상·취향형'), ('SOURCED', '사실·정보형')], default='HYPOTHETICAL', max_length=20, verbose_name='콘텐츠 유형')),
                ('reference_url', models.URLField(blank=True, help_text='사실·정보형 콘텐츠는 신뢰할 수 있는 근거 URL이 필요합니다.', verbose_name='검증 자료 URL')),
                ('status', models.CharField(choices=[('PENDING', '검수 대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='PENDING', max_length=10, verbose_name='검수 상태')),
                ('moderation_note', models.TextField(blank=True, verbose_name='검수 메모')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검수일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='제출일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_sets', to='양자택일.category', verbose_name='카테고리')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_game_sets', to=settings.AUTH_USER_MODEL, verbose_name='제작자')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_game_sets', to=settings.AUTH_USER_MODEL, verbose_name='검수자')),
            ],
            options={
                'verbose_name': '사용자 제작 게임 세트',
                'verbose_name_plural': '사용자 제작 게임 세트 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='game_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='양자택일.gameset', verbose_name='사용자 제작 세트'),
        ),
    ]
