# Generated by Django 5.2.16 on 2026-07-24 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('양자택일', '0002_add_user_game_sets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameset',
            options={
                'ordering': ['-created_at'],
                'verbose_name': '게임 세트',
                'verbose_name_plural': '게임 세트 목록',
            },
        ),
        migrations.AddField(
            model_name='gameset',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='공식 콘텐츠'),
        ),
        migrations.AlterField(
            model_name='gameset',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_game_sets', to=settings.AUTH_USER_MODEL, verbose_name='제작자'),
        ),
    ]
