# Generated by Django 5.2 on 2026-07-25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('양자택일', '0004_saved_instant_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedinstantresult',
            name='game_data',
            field=models.JSONField(default=dict, verbose_name='게임 문항과 답변'),
        ),
        migrations.AddField(
            model_name='savedinstantresult',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기'),
        ),
        migrations.CreateModel(
            name='ChoiceComparisonInvite',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='초대 코드',
                    ),
                ),
                (
                    'participant_answers',
                    models.JSONField(default=list, verbose_name='참여자 답변'),
                ),
                (
                    'participant_result',
                    models.JSONField(default=dict, verbose_name='참여자 결과'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('OPEN', '참여 대기'),
                            ('COMPLETED', '비교 완료'),
                        ],
                        default='OPEN',
                        max_length=12,
                        verbose_name='상태',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='초대 생성일',
                    ),
                ),
                (
                    'completed_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='비교 완료일',
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='created_choice_invites',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='초대한 회원',
                    ),
                ),
                (
                    'participant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='joined_choice_invites',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='참여 회원',
                    ),
                ),
                (
                    'source_result',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comparison_invites',
                        to='양자택일.savedinstantresult',
                        verbose_name='초대 원본 결과',
                    ),
                ),
            ],
            options={
                'verbose_name': '친구·연인 함께하기 초대',
                'verbose_name_plural': '친구·연인 함께하기 초대 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
