# Generated by Django 5.2 on 2026-07-25

import django.db.models.deletion
import 양자택일.models
from django.conf import settings
from django.db import migrations, models


def populate_keyword_text(apps, schema_editor):
    SavedInstantResult = apps.get_model('양자택일', 'SavedInstantResult')
    for result in SavedInstantResult.objects.all().iterator():
        keywords = result.keywords if isinstance(result.keywords, list) else []
        result.keyword_text = ' '.join(
            str(keyword).strip()
            for keyword in keywords
            if str(keyword).strip()
        )[:160]
        result.save(update_fields=['keyword_text'])


class Migration(migrations.Migration):

    dependencies = [
        ('양자택일', '0005_member_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedinstantresult',
            name='keyword_text',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=160,
                verbose_name='키워드 검색문',
            ),
        ),
        migrations.RunPython(
            populate_keyword_text,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='choicecomparisoninvite',
            name='status',
            field=models.CharField(
                choices=[
                    ('OPEN', '참여 대기'),
                    ('COMPLETED', '비교 완료'),
                    ('CANCELED', '초대 취소'),
                    ('EXPIRED', '기간 만료'),
                ],
                default='OPEN',
                max_length=12,
                verbose_name='상태',
            ),
        ),
        migrations.AddField(
            model_name='choicecomparisoninvite',
            name='canceled_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='초대 취소일',
            ),
        ),
        migrations.AddField(
            model_name='choicecomparisoninvite',
            name='creator_seen_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='초대자 결과 확인일',
            ),
        ),
        migrations.AddField(
            model_name='choicecomparisoninvite',
            name='expires_at',
            field=models.DateTimeField(
                default=양자택일.models.default_invite_expiry,
                verbose_name='초대 만료일',
            ),
        ),
        migrations.CreateModel(
            name='MemberGameEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'game_token',
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name='즉석 게임 식별자',
                    ),
                ),
                (
                    'keyword',
                    models.CharField(
                        max_length=30,
                        verbose_name='키워드',
                    ),
                ),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('STARTED', '게임 시작'),
                            ('COMPLETED', '게임 완료'),
                        ],
                        max_length=12,
                        verbose_name='이벤트 종류',
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name='추천 출처',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='발생일',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='member_game_events',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='회원',
                    ),
                ),
            ],
            options={
                'verbose_name': '회원 게임 이벤트',
                'verbose_name_plural': '회원 게임 이벤트 목록',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['user', 'event_type', '-created_at'],
                        name='member_event_user_type_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=(
                            'user',
                            'game_token',
                            'keyword',
                            'event_type',
                        ),
                        name='unique_member_game_event_stage',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'keyword',
                    models.CharField(
                        max_length=30,
                        verbose_name='추천 키워드',
                    ),
                ),
                (
                    'rating',
                    models.CharField(
                        choices=[
                            ('LIKE', '관심 있음'),
                            ('HIDE', '관심 없음'),
                        ],
                        max_length=8,
                        verbose_name='선호도',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='최초 입력일',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='최근 수정일',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recommendation_feedback',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='회원',
                    ),
                ),
            ],
            options={
                'verbose_name': '추천 선호 피드백',
                'verbose_name_plural': '추천 선호 피드백 목록',
                'ordering': ['-updated_at'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'keyword'),
                        name='unique_recommendation_feedback_per_keyword',
                    ),
                ],
            },
        ),
    ]
